version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    groups:
      root-go-modules:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    groups:
      example-go-modules:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/contrib/otel"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    groups:
      otel-go-modules:
        patterns:
          - "*"
