version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec
    - misspell

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    govet:
      disable:
        - fieldalignment
        - shadow
        - nilness
        - unusedwrite
    staticcheck:
      checks:
        - "all"
        - "-SA4023"
        - "-SA4031"
        - "-QF1011"
    gosec:
      excludes:
        - G104  # Audit errors not checked (covered by errcheck)
        - G304  # File path from variable (necessary for config loading)
        - G101  # False positive: env var names, not credentials
        - G404  # Retry jitter doesn't need cryptographic randomness

  exclusions:
    rules:
      # Allow unchecked errors in tests
      - path: _test\.go
        linters:
          - errcheck
      # Allow relaxed permissions in tests (test data files)
      - path: _test\.go
        linters:
          - gosec
        text: "G301|G306"
      # Project scaffolding needs standard permissions (0755 dirs, 0644 files)
      - path: cli/commands/init\.go
        linters:
          - gosec
        text: "G301|G306"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/petal-labs/iris
